# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.glycemie_voter:
        class:  DiabeteHelperBundle\Security\GlycemieVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    app.meal_voter:
        class:  DiabeteHelperBundle\Security\MealVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    twig.json_decode:
        class: DiabeteHelperBundle\Twig\Extension\JsonDecode
        tags:
            - { name: twig.extension }