DiabeteHelperBundle\Entity\Meal:
    type: entity
    repositoryClass: DiabeteHelperBundle\Repository\MealRepository
    table:  meal
    indexes:
        FK_user_id:
            columns:
                - iduser
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id
            generator:
                strategy: IDENTITY

    fields:
        carbohydrate:
            type: decimal
            nullable: false
            precision:  10
            scale:  2
            column: carbohydrate
        estimatedMealBolus:
            type: decimal
            nullable: true
            precision:  10
            scale:  2
            column: estimatedMealBolus
        dateMeal:
            type: datetime
            nullable: false
            options:
                default:  null
            column: dateMeal
    manyToOne:
        iduser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: id
            inversedBy: null
            joinColumns:
                iduser:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
