DiabeteHelperBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id
            generator:
                strategy: IDENTITY
    fields:
        weight:
            type: decimal
            nullable: true
            precision: 4
            scale: 2
            column: weight
        height:
            type: decimal
            nullable: true
            precision: 4
            scale: 2
            column: height
        yearofbirth:
            type: datetime
            nullable: true
            column: year_of_birth
        bloodType:
            type:  string
            nullable: true
            length: 10
            column: bloodType
        lastHb1c:
            type:  decimal
            nullable: true
            precision: 4
            scale: 2
            column: lastHb1c
        lastHb1cDate:
            type: datetime
            nullable: true
            options:
                default: null
            column: lastHb1cDate
        typeDiabete:
            type: string
            nullable: true
            length: 50
            column: typeDiabete
        typeTraitement:
            type: string
            nullable: true
            length: 255
            column: typeTraitement
        insulinSensivity:
            type: decimal
            nullable: true
            precision:  10
            scale:  2
            column: insulinSensivity
        glycemicObjective:
            type: decimal
            nullable: true
            precision:  10
            scale:  2
            column: glycemicObjective
        dateInscription:
            type: datetime
            nullable: true
            options:
                default: null
            column: dateInscription
    lifecycleCallbacks: {  }
