<?php

namespace DiabeteHelperBundle\Repository;

/**
 * GlycemieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlycemieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGlycemiesByDates(
        $dateStart = NULL,
        $dateEnd = NULL,
        $idUser
    )
    {
        $qb = $this->createQueryBuilder('glycemie')
            ->andWhere('glycemie.iduser = :iduser')
            ->andWhere('glycemie.dateGlycemie BETWEEN :start AND :end')
            ->setParameter('iduser', $idUser)
            ->setParameter('start', $dateStart->format('Y-m-d'))
            ->setParameter('end', $dateEnd->format('Y-m-d'));

        return $qb->getQuery()->execute();
    }
}
