<?php

namespace DiabeteHelperBundle\Repository;

/**
 * GlycemieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlycemieRepository extends \Doctrine\ORM\EntityRepository
{
  public function findGlycemiesByDates($dateStart = NULL, $dateEnd = NULL, $idUser = NULL)
  {
    return $this->getEntityManager()
      ->createQuery(
        "
SELECT g FROM DiabeteHelperBundle:Glycemie g 
WHERE g.iduser = ". $idUser ." AND g.dateGlycemie BETWEEN '". $dateStart->format('Y-m-d') ."' AND '". $dateEnd->format('Y-m-d') ."' 
ORDER BY g.dateGlycemie DESC
"
      )
      ->getResult();
  }
}
